name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Build and push Docker images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

        # Build and push Product Service
        docker build -t $DOCKER_USERNAME/product-service:latest -f ProductService/Dockerfile .
        docker push $DOCKER_USERNAME/product-service:latest

        # Build and push Order Service
        docker build -t $DOCKER_USERNAME/order-service:latest -f OrderService/Dockerfile .
        docker push $DOCKER_USERNAME/order-service:latest

        # Build and push User Service
        docker build -t $DOCKER_USERNAME/user-service:latest -f UserService/Dockerfile .
        docker push $DOCKER_USERNAME/user-service:latest

        # Build and push Payment Service
        docker build -t $DOCKER_USERNAME/payment-service:latest -f PaymentService/Dockerfile .
        docker push $DOCKER_USERNAME/payment-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.19.0'

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
